"""Dependency-free bundle: ESM, classic IIFE and wheel assets from same source."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
def read(path): return (ROOT/path).read_text(encoding='utf-8')
def literal(value): return json.dumps(value,ensure_ascii=True,separators=(',',':')).replace('<','\\u003c').replace('>','\\u003e').replace('&','\\u0026')
source=read('web/player/src/validate.js')+'\n'+read('web/player/src/player.js')
source=source.replace('__TRACE_SCHEMA__',literal(json.loads(read('schemas/trace.schema.json')))).replace('__PLAYER_CSS__',literal(read('web/player/src/player.css'))).replace('__COASTLINES__',literal(json.loads(read('web/assets/coastlines.json'))))
classic='/* Generated by tools/build_player.py. See THIRD_PARTY_NOTICES.md. */\n(function(global){\n"use strict";\n'+source+'\nglobal.SatNetEduPlayer={createPlayer,validateTrace};\n})(globalThis);\n'
esm='/* Generated; same implementation as the classic bundle. */\n'+source+'\nexport {createPlayer,validateTrace};\n'
for folder,body in [('web/player/dist',classic),('web/player/dist/esm',esm),('src/satnet_edu/assets',classic)]:
    p=ROOT/folder;p.mkdir(parents=True,exist_ok=True);(p/'satnet-edu-player.js').write_text(body,encoding='utf-8')
(ROOT/'web/player/dist/esm/package.json').write_text('{"type":"module"}\n',encoding='utf-8')
print('Built classic, ESM and wheel player assets')
